### ISSUE TITLE
(URGENT) mnconvert release-tag workflow failing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert-ruby#10]
https://github.com/metanorma/mnconvert-ruby/actions/runs/1882902085

**Comment by CAMOBAP** [comment]
@ronaldtse maybe you can share some details on new bot which do gh-pages deployment?

I see that it put documents in `site` directory (not just in root), this is why all links are broken

I am sure that we should fix original problem and not just links in Rakefile

**Comment by CAMOBAP** [comment]
Release done

**Comment by ronaldtse** [comment]
> @ronaldtse maybe you can share some details on new bot which do gh-pages deployment?

The metanorma-ci user. The `metanorma site generate` command always puts in the `site` directory, that is correct. We just need to change the pages deployment workflow to publish the `site` directory.
