### ISSUE TITLE
Add spec/fixtures/rfc8650.xml back in to repo

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mnconvert-ruby#11]
I can't run rspec on it. How is GitHub Actions able to work around this?

**Comment by ronaldtse** [comment]
Why are we running an RFC in mnconvert?

**Comment by CAMOBAP** [comment]
@opoudjis I'm able to run test locally, three is nothing hacky in workflow according to Rakefile it will be downloaded for regular `bundle exec rake`

Maybe you can share more details about the issue?

**Comment by CAMOBAP** [comment]
> Why are we running an RFC in mnconvert?

As far as I remember it was in mn2pdf or mn2sts tests, so I moved it here, if it can be skipped I can remove this test

**Comment by ronaldtse** [comment]
mnconvert includes functionality that converts RFC XML into MN Adoc, perhaps it is trying to test that? If that's the case it is a valid test.

**Comment by CAMOBAP** [comment]
Tests for rfc8650 passed locally and on CI. spec/fixtures/rfc8650.xml installs with Rakefile
