### ISSUE TITLE
(URGENT) Failed action in tag_repo step

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert-ruby#17]
Looks like the release action failed at: https://github.com/metanorma/mnconvert-ruby/actions/runs/3981275258

@CAMOBAP can you have a look? Thanks.

**Comment by Intelligent2013** [comment]
This issue occurs due validation errors:
```
Validate XML against DTD /home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee/stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd...
       /tmp/rspec-20230123-1830-1cv3nth/p9[87](https://github.com/metanorma/mnconvert-ruby/actions/runs/3981275258/jobs/6839732837#step:10:88).6.xml is NOT valid reason:
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 47; Attribute "xmlns:tbx" must be declared for element type "front".
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 828; columnNumber: 46; Attribute "xmlns:tbx" must be declared for element type "body".
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1621; columnNumber: 46; Attribute "xmlns:tbx" must be declared for element type "back".
```
I'll fix it.

**Comment by CAMOBAP** [comment]
@Intelligent2013 I have tried to reproduce it locally, but all tests passed, maybe I missing something?

**Comment by Intelligent2013** [comment]
I've downloaded artifact [ieee-test-input](https://github.com/metanorma/mnconvert-ruby/suites/10514690209/artifacts/523354557) from page https://github.com/metanorma/mnconvert-ruby/actions/runs/3981275258 and tried to run mnconvert on xml from .zip - the error occurs. In progress...

**Comment by Intelligent2013** [comment]
Strange namespaces in the resulted XML:
```
<front xmlns:tbx="urn:iso:std:iso:30042:ed-1">
...
<body xmlns:tbx="urn:iso:std:iso:30042:ed-1">
...
<back xmlns:tbx="urn:iso:std:iso:30042:ed-1">
```
Will investigate.

**Comment by Intelligent2013** [comment]
Fixed: https://github.com/metanorma/mnconvert-ruby/actions/runs/3990590111
