### ISSUE TITLE
Failure to tag repo in auto action

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert-ruby#19]
Ping @CAMOBAP on this:
* https://github.com/metanorma/mnconvert-ruby/actions/runs/4265586393

**Comment by CAMOBAP** [comment]
Already fixed in 470299b96bd5dd54a8ac7510a922ba69ca226318

And released manually

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !
