### ISSUE TITLE
Fix code scanning alert - Unsafe shell command constructed from library input

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mnconvert-ruby#21]
Tracking issue for:
- [ ] https://github.com/metanorma/mnconvert-ruby/security/code-scanning/1

**Comment by Intelligent2013** [comment]
The same issue occurred for `mn2pdf-ruby` in https://github.com/metanorma/mn2pdf-ruby/security/code-scanning/4 too, closed as `false positive`, `args input under library control and not exposed in API`.
