### ISSUE TITLE
Test "MnConvert converts XML to STS without specifying output" failed

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mnconvert-ruby#23]
### Intro

After updating URL for `spec/fixtures/rice-en.cd.mn.xml`

- from `https://raw.githubusercontent.com/metanorma/mn-samples-iso/gh-pages/documents/international-standard/rice-en.cd.xml
-  to `https://raw.githubusercontent.com/metanorma/mn-samples-iso/gh-pages/documents/international-standard/rice-2023/document-en.cd.xml`

 
in https://github.com/metanorma/mnconvert-ruby/commit/37495c13b1654304aabe6dc199f7432baa057308, test "MnConvert converts XML to STS without specifying output" starts failing 

https://github.com/metanorma/mnconvert-ruby/actions/runs/10799589103/job/29955750148#step:5:52

**Comment by CAMOBAP** [comment]
@Intelligent2013 could you please help with investigation

**Comment by Intelligent2013** [comment]
Very strange...
The issue fixed already (https://github.com/metanorma/mnconvert/issues/414) in the version https://github.com/metanorma/mnconvert/releases/tag/v1.63.0.
Will investigate..

**Comment by CAMOBAP** [comment]
@Intelligent2013 my bad it happens because the release is failed, after I did manual release it passed https://github.com/metanorma/mnconvert-ruby/actions/runs/10800266707/job/29957953716
