### ISSUE TITLE
Add tests and a validation step for RFC XML (as an input format)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert-ruby#3]
We should add tests and a validation step for RFC XML (as an input format) as well, in a new issue.

_Originally posted by @ronaldtse in https://github.com/metanorma/mnconvert-ruby/issues/2#issuecomment-976662775_

**Comment by Intelligent2013** [comment]
@ronaldtse @CAMOBAP when input format if RFC XML, then mnconvert checks RFC XML against RelaxNG schema before converting.

**Comment by CAMOBAP** [comment]
Done
